---
- name: dnsmasq configuration (/etc/dnsmasq.conf)
  template: >
    dest=/etc/dnsmasq.conf
    src=dnsmasq.conf.j2
    backup=yes
    validate="dnsmasq --test -C %s"
  notify: restart dnsmasq
  when: ansible_distribution != 'SmartOS'

- name: dnsmasq configuration (/opt/local/etc/dnsmasq.conf)
  template: >
    dest=/opt/local/etc/dnsmasq.conf
    src=dnsmasq.conf.j2
    backup=yes
    validate="dnsmasq --test -C %s"
  notify: restart dnsmasq
  when: ansible_distribution == 'SmartOS'
